# Generated by Django 4.1.3 on 2022-12-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
